version: 2.1
jobs: 
  
  run_unit_tests:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
  
  run_tests:
    docker:
      - image: circleci/node:10-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  

      - run:
          command: yarn start
          background: true
          
  run_chromatic_tests:
    docker:
        - image: circleci/node:10-browsers

    steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

        - run: yarn install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}
        
        - run: npm run chromatic --exit-zero-on-changes

  run_applitools_tests:
    docker:
        - image: circleci/node:10-browsers
    steps:
        - checkout

        - restore_cache:
            keys:
              - v1-dependencies-{{ checksum "package.json" }}
              - v1-dependencies-

        - run: yarn install

        - save_cache:
            paths:
              - node_modules
            key: v1-dependencies-{{ checksum "package.json" }}

        - run: 
            command: echo "export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1"
        
        - run: 
            command: echo $APPLITOOLS_BATCH_ID
         
        - run: 
            command: echo $CIRCLE_SHA1

        - run:
            command: yarn start
            background: true

        - run: 
            command: |
              echo "export APPLITOOLS_BATCH_ID=$CIRCLE_SHA1"
              node tests/applitools/visualgrid-storybook-async.js


workflows:
 test:
   jobs:
     - run_unit_tests
     - run_tests
     - run_applitools_tests
